repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: double-quote-string-fixer  # for single quotes: uncomment and add black config “skip-string-normalization”
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-summaries=100", "--wrap-descriptions=100", "--config=./pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v6.0.0.post1
    hooks:
      - id: pyproject-flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [css, javascript]
